[workspace]
members = [
  "bins/*",
  "xtask",
  "."
]

[package]
name = "stackable"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
which = { workspace = true }

[workspace.dependencies]
serde = { version = "1.0.160", features = ["derive"] }
clap = { version = "4.2.1", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
anyhow = "1.0.70"
which = "4.4.0"
