[workspace]
members = [
  "bins/*",
  "xtask",
  "."
]

[package]
name = "stackable"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
which = { workspace = true }
serde = { workspace = true }
url = { workspace = true }

[build-dependencies]
gobuild = "0.1.0-alpha.1"

[workspace.dependencies]
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.16", features = ["native-tls"] }
serde = { version = "1.0.160", features = ["derive"] }
indexmap = { version = "1.9.3", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive"] }
tracing-subscriber = "0.3.17"
clap_complete = "4.2.0"
async-trait = "0.1.68"
lazy_static = "1.4.0"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
dotenvy = "0.15.7"
tracing = "0.1.37"
anyhow = "1.0.70"
which = "4.4.0"
url = "2.3.1"
xdg = "2.4.1"
