[package]
name = "xtask"
version = "0.0.1"
edition = "2021"

[dependencies]
stackablectl = { path = "../bins/stackablectl" }
clap_complete =  { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
clap_mangen = "0.2.10"
